---
title: "EGU 2019 plots"
author: "Beni Stocker"
date: "`r Sys.Date()`"
output:
  html_document:
    # theme: cosmo  #paper
    toc: true
    toc_float: true
    toc_depth: 4
# output:
#   pdf_document:
#     toc: true
#     toc_depth: 2
header-includes:
   - \usepackage{amsmath}
---

```{r setup, include=FALSE}
library(dplyr)
source("scn_model.R")
knitr::opts_chunk$set(echo = TRUE)
```

## sCN model run

### Simulation settings.
```{r}
settings <- list(
  # ntsteps = 5000
  spinupyears = 3000,
  nyeartrend  = 750,
  out_spinup  = FALSE,
  yr_soileq   = 600
  )
```

### Model parameters
```{r}
par <- list(
  r_cton_plant = 30,
  r_cton_soil  = 10,
  tau_plant    = 10,
  tau_soil_c   = 3,
  tau_soil_n   = 9,
  tau_labl     = 0.5,
  sla          = 0.1,
  eff          = 1.0,
  kl           = 50,
  kr           = 80,
  alpha_fix    = 0.6    # only used for "conly" method
)
```

### Environmental conditions and treatment
```{r}
ppfd <- 90
lue  <- 1.0
lue_manip <- rep(1, settings$nyeartrend); lue_manip[101:settings$nyeartrend] <- 1.1
n_in <- 0.8
n_in_manip <- rep(0.8, settings$nyeartrend); n_in_manip[101:settings$nyeartrend] <- 0.9
```

### Model run
```{r}
## N fertilisation run
df_scn_fert <- scn_model( ctot0=100, csoil0=100, 
                     ppfd=ppfd, lue=lue, n_in=n_in_manip, 
                     par=par, settings=settings, method="scn", accelerate=FALSE
                     )

## "CO2" run
df_scn_co2 <- scn_model( ctot0=100, csoil0=100, 
                     ppfd=ppfd, lue=lue_manip, n_in=n_in, 
                     par=par, settings=settings, method="scn", accelerate=FALSE
                     )

## CO2 run with slow decomposition rate
par_slow <- par
par_slow$tau_soil_c <- par$tau_soil_c * 5
par_slow$tau_soil_n <- par$tau_soil_n * 5

df_scn_co2_slow <- scn_model( ctot0=100, csoil0=100, 
                     ppfd=ppfd, lue=lue_manip, n_in=n_in, 
                     par=par_slow, settings=settings, method="scn", accelerate=FALSE
                     )

# df_scn_acc <- scn_model(  ctot0=100, csoil0=100, 
#                           ppfd=ppfd, lue=lue, n_in=n_in, 
#                           par=par, settings=settings, method="scn", accelerate=TRUE
#                         )
```

### Plot

#### N fertilisation

```{r}
library(ggplot2)
ggplot( data = df_scn_fert, aes(x=simyear, y=cplant_ag)) +
  geom_line( size=1 ) +
  labs(title="Aboveground plant C", 
       x="Simulation Year", 
       y=expression(paste("C pool (g C m"^{-2}, ")")),
       subtitle = "N fertilisation at year 100") +
  expand_limits(y=0) +
  geom_vline(xintercept = 100, linetype="dotted")
ggsave("abgm_nfert.pdf", width=4, height=3)

df_scn_fert %>% 
  rowwise() %>% 
  mutate( ndemand = npp / par$r_cton_plant ) %>% 
  select(simyear, ndemand, nup) %>% 
  tidyr::gather(varnam, value, c(nup, ndemand)) %>% 
  ggplot( aes(x=simyear, y=value, color=varnam)) +
  geom_line( size=1 ) +
  labs(title="N supply = N demand", 
       x="Simulation Year", 
       y=expression(paste("N flux (g N m"^{-2}, " yr"^{-1}, ")")),
       subtitle = "N fertilisation at year 100") +
  expand_limits(y=0) +
  geom_vline(xintercept = 100, linetype="dotted")
ggsave("n_supply_demand_nfert.pdf", width=4, height=3)
```

#### Elevated CO2

```{r}
ggplot( data = df_scn_co2, aes(x=simyear, y=cplant_ag)) +
  geom_line( size=1 ) +
  labs(title="Aboveground plant C", 
       x="Simulation Year", 
       y=expression(paste("C pool (g C m"^{-2}, ")")),
       subtitle = expression(paste("Elevated CO"[2], " after year 100"))) +
  expand_limits(y=0) +
  geom_vline(xintercept = 100, linetype="dotted")
ggsave("abgm_co2.pdf", width=4, height=3)

ggplot( data = df_scn_co2, aes(x=simyear, y=nup)) +
  geom_line( size=1 ) +
  labs(title="N uptake", 
       x="Simulation Year", 
       y=expression(paste("N flux (g N m"^{-2}, " yr"^{-1}, ")")),
       subtitle = expression(paste("Elevated CO"[2], " after year 100"))) +
  expand_limits(y=0) +
  geom_vline(xintercept = 100, linetype="dotted")
ggsave("nup_co2.pdf", width=4, height=3)

ggplot( data = df_scn_co2, aes(x=simyear, y=cplant_bg/nup)) +
  geom_line( size=1 ) +
  labs(title="N cost", 
       x="Simulation Year", 
       y=expression(paste("g C yr g N"^{-1})),
       subtitle = expression(paste("Elevated CO"[2], " after year 100"))) +
  expand_limits(y=0) +
  geom_vline(xintercept = 100, linetype="dotted")
ggsave("ncost_co2.pdf", width=4, height=3)
```

#### Slow decomposition rate

```{r}
df_scn_co2 %>% 
  select(simyear, cplant_ag) %>% 
  left_join( select( df_scn_co2_slow, simyear, cplant_ag_slow=cplant_ag ), by="simyear" ) %>%
  tidyr::gather(varnam, value, c(cplant_ag, cplant_ag_slow)) %>% 
  ggplot( aes(x=simyear, y=value, color=varnam)) +
  geom_line( size=1 ) +
  labs(title="Aboveground plant C", 
       x="Simulation Year", 
       y=expression(paste("C pool (g C m"^{-2}, ")")),
       subtitle = expression(paste("Elevated CO"[2], " after year 100"))) +
  expand_limits(y=0) +
  geom_vline(xintercept = 100, linetype="dotted") +
  scale_color_discrete(name="", breaks=c("cplant_ag", "cplant_ag_slow"), labels=c("Fast soil turnover", "Slow soil turnover"))
ggsave("abgm_co2_slow.pdf", width=4, height=3)
```


```{r}
df_scn %>%
  tidyr::gather(varnam, value, c(cplant_ag, cplant_bg)) %>% 
  ggplot( aes(x=simyear, y=value, color=varnam)) +
  geom_line() +
  labs(title="Plant C", x="Simulation Year", y=expression(paste("C pool (g C m"^{-2}, ")"))) +
  expand_limits(y=0)

df_scn %>% 
  ggplot( aes(x=simyear, y=nloss) ) +
  geom_line() +
  labs(title="N losses", x="Simulation Year", y=expression(paste("N flux (g N m"^{-2}, " yr"^{-1}, ")"))) +
  geom_hline(yintercept = n_in, linetype="dotted") +
  expand_limits(y=0)

df_scn %>% 
  ggplot( aes(x=simyear, y=cplant_bg/cplant_ag) ) +
  geom_line() +
  labs(title="Root:shoot ratio", x="Simulation Year", y="ratio (unitless)") +
  expand_limits(y=0)

df_scn %>% 
  ggplot( aes(x=simyear, y=csoil) ) +
  geom_line() +
  labs(title="Soil C", x="Simulation Year", y=expression(paste("C pool (g C m"^{-2}, ")"))) +
  expand_limits(y=0)

gg <- ggplot() +
  geom_line( data=df_scn, aes(x=simyear, y=nsoil) ) +
  labs(title="Soil N", x="Simulation Year", y=expression(paste("N pool (g N m"^{-2}, ")"))) +
  geom_line( data=df_scn_acc, aes(x=simyear, y=nsoil), linetype="dashed") +
  geom_vline(xintercept = ifelse(settings$out_spinup, settings$spinupyears, 0), linetype="dotted") +
  expand_limits(y=0)
print(gg)

gg <- ggplot() +
  geom_line( data=df_scn, aes(x=simyear, y=nup) ) +
  labs(title="N uptake", x="Simulation Year", y=expression(paste("N flux (g N m"^{-2}, " yr"^{-1}, ")"))) +
  geom_vline(xintercept = ifelse(settings$out_spinup, settings$spinupyears, 0), linetype="dotted") +
  expand_limits(y=0)
print(gg)

df_scn %>% 
  ggplot( aes(x=simyear, y=clabl) ) +
  geom_line() +
  labs(title="Labile C", x="Simulation Year", y=expression(paste("C pool (g C m"^{-2}, ")"))) +
  expand_limits(y=0)

# df_scn %>% 
#   ggplot( aes(x=simyear, y=clabl/nlabl) ) +
#   geom_line() +
#   labs(title="Labile C:N", x="Simulation Year", y=expression(paste("C:N ratio (g C g N"^{-1}, ")"))) +
#   geom_hline(yintercept=par$r_cton_plant, linetype="dotted") +
#   expand_limits(y=0)
# 
# soil_cton_expected <- par$r_cton_plant * par$tau_soil_c / par$tau_soil_n
# df_scn %>% 
#   ggplot( aes(x=simyear, y=csoil/nsoil) ) +
#   geom_line() +
#   labs(title="Soil C:N", x="Simulation Year", y=expression(paste("C:N ratio (g C g N"^{-1}, ")"))) +
#   geom_hline(yintercept=soil_cton_expected, linetype="dotted") +
#   expand_limits(y=0)
# 
# df_scn %>% 
#   ggplot( aes(x=simyear, y=c_litterfall/n_litterfall) ) +
#   geom_line() +
#   labs(title="Litterfall C:N", x="Simulation Year", y=expression(paste("C:N ratio (g C g N"^{-1}, ")"))) +
#   geom_hline(yintercept=par$r_cton_plant, linetype="dotted") +
#   expand_limits(y=0)
# 
# df_scn %>% 
#   ggplot( aes(x=simyear, y=(cplant_ag+cplant_bg)/(nplant_ag+nplant_bg)) ) +
#   geom_line() +
#   labs(title="Plant C:N", x="Simulation Year", y=expression(paste("C:N ratio (g C g N"^{-1}, ")"))) +
#   expand_limits(y=0)


netmin_expected <- n_in + par$r_cton_plant^(-1) * (tail(df_scn$cplant_ag, 1) + tail(df_scn$cplant_bg, 1))/par$tau_plant
df_scn %>% 
  ggplot( aes(x=simyear, y=netmin) ) +
  geom_line() +
  labs(title="Net N mineralization", x="Simulation Year", y=expression(paste("N flux (g N m"^{-2}, " yr"^{-1}, ")"))) +
  geom_hline(yintercept = netmin_expected, linetype="dotted") +
  expand_limits(y=0)

```
